**LABORATORIO 2: RETOS**


---

**PARTICIPANTES:**

---

1. JUAN PABLO QUINTERO
2. MATEO VALDERRAMA CABRERA
3. JULIAN STIVEN VIRGUEZ PATIÑO
4. DAVID NUÑEZ MEJIA
5. MONICA CONSTANZA CRUZ PARRA
6. DIEGO LEANDRO LUNA CUBILLOS

**GRUPO: 4**

---

**DOCENTE:**

1.1 DIEGO CAMILO TALERO OSORIO

---


**PROGRAMACION DE COMPUTADORES/ GR 14.**


---

**RECOMENDACIONES:**
1. Cumplir con cada uno de los 9 retos en sus grupos de trabajo
y subir el Colab a el repositorio grupal,
for: 28/09/2022 12:59

2. No se pueden usar funciones() predefinidas de python, que ejecuten el algoritmo, sin ustedes entender antes la manera de resolverlo con codigo.


---

**RETO 1:**
1. Defina un histograma de procedimiento () que tome una lista de números enteros e imprima un histograma en la pantalla. Ejemplo: procedimiento ([4, 9, 7]) debe imprimir lo siguiente:

![image.png]()

In [ ]:
lista = [4,9,7]# Inicialamente se define la lista de valores que imprimira el histograma en este caso ([4, 9, 7]). No se crea un input pero los valores pueden modificarse al cambiar los que stan dentro de la cadena [4,9,7]. 
def histogram(lista):# Se define un def para la funcion nueva que sera la lista del histograma(Usamos el def dado que es la variable de iniciacion que nos brindo el ejemplo (def histogram (lista):).
    for mm in range(len(lista)): # Se crea un for lista en el que se genera un bucle llamado mm en el que se recorrera un listado de números o de datos. A posteriori un len para indicar la cantidad de valores en la lista de entrada ([4, 9, 7])
        print (lista[mm]*'*') # Se imprime el resultado del for len dentro de mm usando el '*' que nos permite procesar el conjunto de datos y es como si fuera un determinante que dice si o no sin usar el while pasa directamente a decir que todos es si y impimir los valores que se le digiten. 
histogram(lista)# Finalemnte se imprime el histograma con los valores enteros de las lista dando el resultado sugerido en el ejemplo.
 # NOTA:
 #1: Se pudo usar un while x > 0  y igualarlo a x-1 pero eran mas lineas de codigo innecesarias por ende se opto por el len que leyera de una vez los enteros.

****
*********
*******

**RETO 2:**
2. Escriba una función long_long() que tome una lista de palabras y devuelva la más larga.

In [ ]:
def longer_long(lista): #se define la funcion 'longer_long' con el argumento 'lista' con el c ual se ejecutaran las condiciones
  mas_larga="" #se defini una variable
  x=lista.split() #se define una segunda variable en donde 'split' dividira o separara la lista introducida en partes
  mas_larga = x[0] #se hace una igualacion entre las dos variables y se le define un valor a x
  for i in range(1, len(x)): #se crea un bucle el cual recorre los datos introducidos y se le aplica un rango y 'len' para que devuelva los datos
    if len(mas_larga)<len(x[i]): #se estable una condicion y se introducen 'len' para que compare y devuelva los valores 
      mas_larga=x[i] #se hace una igualacion y a 'x' se le coloca el valor definido en el bucle
  return mas_larga #se usa el 'return' para que retorne la igualacion
l=input('Introduzca una lista de palabras:') #se define la lista de la funcion mediante valores que se le piden al operador
print('La palabra mas larga es:',longer_long(l)) #se imprime  el resultado

Introduzca una lista de palabras:Buenas tardes
La palabra mas larga es: Buenas

**RETO 3:**
3. Escriba un programa que le diga al usuario que ingrese una cadena. El programa tiene que evaluar la cadena y decir cuántas letras mayúsculas tiene.

In [ ]:
def filt_words(lista, n): # se define la funcion y su argumento
  c={'numero de mayusculas':0} #se crea una variable que se refiera a las mayusculas y su cantidad
  for x in lista: #se crea un bucle que que recorra los datos que se ingresen
    if x.isupper(): #se crea una condicion, para la condicion se utiliza el 'isupper' para que este devuelva los valores que se encuentran en mayuscula 
      c['numero de mayusculas']+=1 # se plante una ecuacion 
  return c # se retornan los valores definidos en c tras las condiciones
f=input("ingrese una cadena:") # se define una variable la cual se encargara de interactuar con el operador
n=0 #se le define un valor a n
print(filt_words(f, n)) #se hace la invocacion de la funcion y se imprime

ingrese una cadena:Hi my Brothers
{'numero de mayusculas': 2}

**RETO 4:**
4. Cree un pequeño programa que convierta números binarios en enteros. Ejemplo:

#![image.png]()

In [ ]:
def para_decimal(binario): #Se crea la funcion 'para_decimal' con el argumento 'binario' que es el que llevara las condiciones
    list = [] #La lista se crea para almacenar los valores que se anadiran 

    for j, i in enumerate(binario[::-1]): #El ciclo for se usa para empezar a operar los valores tal como se haria en una operacion a mano. Se dan dos variables 'j' e 'i'. La funcion de phyton 'enumerate' ayuda a separar los valores del numero binario. Y finalmente el'::-1' se usa para que empiece a tomar los valores de atras para adelante
        a = 2** j # Se define una anueva variable 'a' en la cual se va a elevar el numero de la variable j a la 2
        multiplicacion = int(i)*a #Se convierte en entero la variable 'i' para poderlo multiplicar por la variable creada 'a' y se denomina 'multplicacion' para usarla en el siguiente paso
        list.append(multiplicacion) #Se agregan los valores que dieron de los puntos anteriores a la lista con la funcion 'append'

    return sum(list) #Se usa el 'return' para que retorne el valor de la suma de la lista

x = input('Escibe un numero binario: ') #Se define el input para que el usuario ingrese el numero 
print('El resultado decimal es:',para_decimal(x)) #Dara el reslutado del numero binario en numero decimal

Escibe un numero binario: 110110
El resultado decimal es: 54

**RETO 5:**
5. Cree una función count_vols (), que recibe una palabra y cuenta cuántas letras "a" tiene, cuántas letras "e" tiene, y así hasta completar todas las vocales. Puede hacer que el usuario elija la palabra. solo en minúsculas

In [ ]:
   def contar_vocales(cadena):#se crea la funcion con def usando en este caso el 'contador_vocales' con el argumento 'cadena' que es el que llevara las condiciones
    contador = 0 #se pone el contador desde cero e iniciar el conteo de vocales desde este numero
    for letra in cadena:# el ciclo for se usa para comenzar a pautar las condiciones de el algoritmo
              if letra.lower() in "aeiou":#se establese la condicion para que cuente solo estas letras
                   contador += 1# cada vez que el algoritmo identifica una vocal suma
    total=contador #se suma el total de vocales
    return total#se retorna el total de veces que hay vocales en la palabra ingresada
cadena = input("Ingrese la palabra a evaluar:")#se crea un input que sera la palabra escrita por el usuario que ejecuta el algortimo y esa palabra es el agumento cadena
cantidad = contar_vocales(cadena)#se usa el 'contador_vocales' y el argumento nuevamente para dar la cantidad de vocales
print(f"En la cadena '{cadena}'' hay {cantidad} vocales")#se imprime la palabra descrita por el ususario y la cantidad de vocales que lleva

Ingrese la palabra a evaluar:juan alberto
En la cadena 'juan alberto'' hay 5 vocales

**RETO 6:**
6. Escribe una función es bisiesto () que determine si un año dado es un año bisiesto Un año bisiesto es divisible por 4, pero no por 100. También es divisible por 400.

In [ ]:
  año= int (input("Ingrese el año a evaluar: \n")) #se define la variable a la cual se ingresaran valores enteros 
def es_bisiesto(año): #se define la funcion y su argumento
   if año% 4==0 and año% 100!=0: #se establece una condicion 
    return "El año evaluado es bisiesto." #se retorna el valor de la condicion anterior
   elif año%100==0 and año%400==0: #se establece una condicion ejecutando los bloques de comando
        return "El año evaluado es bisiesto."#se retorna el valor de la segunda condicion
   else: #se coloca para controlar el flujo del programa y avarcar las condiciones que no se mensionan
    return "El año evaluado no es bisiesto." #se retorna el valor de las condiciones que abarca el 'else'

print(es_bisiesto(año))#se hace la invocacion de la funcion y se imprime

Ingrese el año a evaluar:
2022
El año evaluado no es bisiesto.

**RETO 7:**
7. Escribe un programa que pida dos palabras y diga si riman o no. Si las tres últimas letras coinciden, tiene que decir que riman. Si sólo coinciden las dos últimas, tiene que decir que riman un poco y si no, que no riman.

EJEMPLO:

![image.png]()

In [ ]:
palabra1 = input("Escriba una palabra ")# Se realiza una variable para la palabra 1
palabra2 = input("Escriba la segunda palabra: ")#Se realiza una variable para la palabra 2
 
tresultimas1 = palabra1[-3:] # Se realizan 4 variables las cuales va a revisar las 3 ultimas letras de las palabras.
tresultimas2 = palabra2[-3:]
tresultimas11 = palabra1[-2:]
tresultimas2 = palabra2[-2:]
 
if tresultimas1 == tresultimas2:# se crea una condicion la cual es que si las tres ultimas de primera palabra son iguales con las tres ultimas de la segunda palabra, las palabras rimas.
    print("Las palabras riman")
elif tresultimas11 == tresultimas2: # Si coinciden 2 letras de las 2 palabras dara como resultado rima un poco.
    print("Las palabras riman un poco")
else:         
    print("Las palabras no riman")#Si no es ninguna de las anteriores su resultado sera las palabras no riman.

Escriba una palabra uno
Escriba la segunda palabra: dos
Las palabras no riman

**RETO 8:**
8. Tiene un programa que pide al usuario una cantidad de dólares, un tipo de interés y un número de años. Muestra en la pantalla cuánto se habrá convertido el capital inicial al cabo de esos años si se aplica cada año el tipo de interés introducido.
Recuerda que un capital C en dólares a un interés de x por ciento durante n años se convierte en C * (1 + x / 100) elevado a n (años). Pruebe el programa sabiendo que una cantidad de 10.000 a 4,5 24.117,14 después de 20 años.

In [ ]:

dinero=float(input("Ingrese su capital: "))#Se realiza un variable la cual sera el capital que ingrese el usuario sera tipo float
xinteres=float(input("Interes: "))#Se realiza una variable para los intereses la cual es tipo float
years=int(input("Ingrese la cantidad de años: "))# Se realiza una variable tipo int para la cantidad de años
operacion=(dinero*(1+xinteres/100)**years)# Operacion matematica la cual dara el resultado 


print('{:,.5f}'.format(operacion).replace(',','.'))#se utiliza '{:,.5f}'.format(operacion).replace(',','.')) para que brinde los 5 ultimos digitos despues del punto, a demas se le agrega el print para ver el resultado

Ingrese su capital: 10.000
Interes: 4.5
Ingrese la cantidad de años: 20
24.11714

In [ ]:
area = 1973.9208802178716
print('El area es: {:,.2f}'.format(area))

El area es: 1,973.92

**RETO 9:**
9. Crear un algoritmo que pida un número el (0 a 100), el programa tiene que crear una tabla de multiplicación del 0 al número seleccionado.

Ejemplo: su número de 0 a 100: 3
0 x 3 = 0

1 x 3 = 3

2 x 3 = 6

3 x 3 = 9

In [ ]:
l=int(input("ingrese número que desea: "))#Se Crea una variable para el numero que se desea 


for M in range(1,l+1):# Se crea un ciclo con un rango desde 1 hasta el numero del usuario +1 
  if l >=101:#Se crea una condicion para que cuando el numero sea mayor a 101 imprima no se puede y con break termine el ciclo
   print("No se puede")
   break
  for A in range(1,11):#Se crea un ciclo con un rango desde 1 hasta 11 para que las tablas aparezcan del uno al 10 este es la segunda columna de las tablas
    print(str(M)+" * " + str(A) + " = " + str(M*A))#se concatena los ciclos M,A a demas se realiza la operacion matematica principal la cual es multiplicar
  print()#se hace un print para crear un espacio en blano y ver la separacion de las tablas

ingrese número que desea: 100
1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70

8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90

10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100

11 * 1 = 11
11 * 2 = 22
11 * 3 = 33
11 * 4 = 44
11 * 5 = 55
11 * 6 = 66
11 * 7 = 77
11 * 8 = 88
11 * 9 = 99
11 * 10 = 110

12 * 1 = 12
12 * 2 = 24
12 * 3 = 36
12 * 4 = 48
12 * 5 = 60
12 * 6 = 72
12 * 7 = 84
12 * 8 = 96
12 * 9 = 108
12 * 10 = 120

13 * 1 = 13
13 * 2 = 26
13 * 3 = 39
13 * 4 = 52
13 * 5 = 65
13 * 6 = 78
13 * 7 = 91
13 * 8 = 104
13 * 9 = 117
13 * 10 = 130

14 * 1 = 14
14 * 2 = 28
14 * 3 = 42
14 * 4 = 56
14 * 5 = 70
14 * 6 = 84
14 * 7 = 98
14 * 8 = 112
14 * 9 = 126
14 * 10 = 140

15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150

16 * 1 = 16
16 * 2 = 32
16 * 3 = 48
16 * 4 = 64
16 * 5 = 80
16 * 6 = 96
16 * 7 = 112
16 * 8 = 128
16 * 9 = 144
16 * 10 = 160

17 * 1 = 17
17 * 2 = 34
17 * 3 = 51
17 * 4 = 68
17 * 5 = 85
17 * 6 = 102
17 * 7 = 119
17 * 8 = 136
17 * 9 = 153
17 * 10 = 170

18 * 1 = 18
18 * 2 = 36
18 * 3 = 54
18 * 4 = 72
18 * 5 = 90
18 * 6 = 108
18 * 7 = 126
18 * 8 = 144
18 * 9 = 162
18 * 10 = 180

19 * 1 = 19
19 * 2 = 38
19 * 3 = 57
19 * 4 = 76
19 * 5 = 95
19 * 6 = 114
19 * 7 = 133
19 * 8 = 152
19 * 9 = 171
19 * 10 = 190

20 * 1 = 20
20 * 2 = 40
20 * 3 = 60
20 * 4 = 80
20 * 5 = 100
20 * 6 = 120
20 * 7 = 140
20 * 8 = 160
20 * 9 = 180
20 * 10 = 200

21 * 1 = 21
21 * 2 = 42
21 * 3 = 63
21 * 4 = 84
21 * 5 = 105
21 * 6 = 126
21 * 7 = 147
21 * 8 = 168
21 * 9 = 189
21 * 10 = 210

22 * 1 = 22
22 * 2 = 44
22 * 3 = 66
22 * 4 = 88
22 * 5 = 110
22 * 6 = 132
22 * 7 = 154
22 * 8 = 176
22 * 9 = 198
22 * 10 = 220

23 * 1 = 23
23 * 2 = 46
23 * 3 = 69
23 * 4 = 92
23 * 5 = 115
23 * 6 = 138
23 * 7 = 161
23 * 8 = 184
23 * 9 = 207
23 * 10 = 230

24 * 1 = 24
24 * 2 = 48
24 * 3 = 72
24 * 4 = 96
24 * 5 = 120
24 * 6 = 144
24 * 7 = 168
24 * 8 = 192
24 * 9 = 216
24 * 10 = 240

25 * 1 = 25
25 * 2 = 50
25 * 3 = 75
25 * 4 = 100
25 * 5 = 125
25 * 6 = 150
25 * 7 = 175
25 * 8 = 200
25 * 9 = 225
25 * 10 = 250

26 * 1 = 26
26 * 2 = 52
26 * 3 = 78
26 * 4 = 104
26 * 5 = 130
26 * 6 = 156
26 * 7 = 182
26 * 8 = 208
26 * 9 = 234
26 * 10 = 260

27 * 1 = 27
27 * 2 = 54
27 * 3 = 81
27 * 4 = 108
27 * 5 = 135
27 * 6 = 162
27 * 7 = 189
27 * 8 = 216
27 * 9 = 243
27 * 10 = 270

28 * 1 = 28
28 * 2 = 56
28 * 3 = 84
28 * 4 = 112
28 * 5 = 140
28 * 6 = 168
28 * 7 = 196
28 * 8 = 224
28 * 9 = 252
28 * 10 = 280

29 * 1 = 29
29 * 2 = 58
29 * 3 = 87
29 * 4 = 116
29 * 5 = 145
29 * 6 = 174
29 * 7 = 203
29 * 8 = 232
29 * 9 = 261
29 * 10 = 290

30 * 1 = 30
30 * 2 = 60
30 * 3 = 90
30 * 4 = 120
30 * 5 = 150
30 * 6 = 180
30 * 7 = 210
30 * 8 = 240
30 * 9 = 270
30 * 10 = 300

31 * 1 = 31
31 * 2 = 62
31 * 3 = 93
31 * 4 = 124
31 * 5 = 155
31 * 6 = 186
31 * 7 = 217
31 * 8 = 248
31 * 9 = 279
31 * 10 = 310

32 * 1 = 32
32 * 2 = 64
32 * 3 = 96
32 * 4 = 128
32 * 5 = 160
32 * 6 = 192
32 * 7 = 224
32 * 8 = 256
32 * 9 = 288
32 * 10 = 320

33 * 1 = 33
33 * 2 = 66
33 * 3 = 99
33 * 4 = 132
33 * 5 = 165
33 * 6 = 198
33 * 7 = 231
33 * 8 = 264
33 * 9 = 297
33 * 10 = 330

34 * 1 = 34
34 * 2 = 68
34 * 3 = 102
34 * 4 = 136
34 * 5 = 170
34 * 6 = 204
34 * 7 = 238
34 * 8 = 272
34 * 9 = 306
34 * 10 = 340

35 * 1 = 35
35 * 2 = 70
35 * 3 = 105
35 * 4 = 140
35 * 5 = 175
35 * 6 = 210
35 * 7 = 245
35 * 8 = 280
35 * 9 = 315
35 * 10 = 350

36 * 1 = 36
36 * 2 = 72
36 * 3 = 108
36 * 4 = 144
36 * 5 = 180
36 * 6 = 216
36 * 7 = 252
36 * 8 = 288
36 * 9 = 324
36 * 10 = 360

37 * 1 = 37
37 * 2 = 74
37 * 3 = 111
37 * 4 = 148
37 * 5 = 185
37 * 6 = 222
37 * 7 = 259
37 * 8 = 296
37 * 9 = 333
37 * 10 = 370

38 * 1 = 38
38 * 2 = 76
38 * 3 = 114
38 * 4 = 152
38 * 5 = 190
38 * 6 = 228
38 * 7 = 266
38 * 8 = 304
38 * 9 = 342
38 * 10 = 380

39 * 1 = 39
39 * 2 = 78
39 * 3 = 117
39 * 4 = 156
39 * 5 = 195
39 * 6 = 234
39 * 7 = 273
39 * 8 = 312
39 * 9 = 351
39 * 10 = 390

40 * 1 = 40
40 * 2 = 80
40 * 3 = 120
40 * 4 = 160
40 * 5 = 200
40 * 6 = 240
40 * 7 = 280
40 * 8 = 320
40 * 9 = 360
40 * 10 = 400

41 * 1 = 41
41 * 2 = 82
41 * 3 = 123
41 * 4 = 164
41 * 5 = 205
41 * 6 = 246
41 * 7 = 287
41 * 8 = 328
41 * 9 = 369
41 * 10 = 410

42 * 1 = 42
42 * 2 = 84
42 * 3 = 126
42 * 4 = 168
42 * 5 = 210
42 * 6 = 252
42 * 7 = 294
42 * 8 = 336
42 * 9 = 378
42 * 10 = 420

43 * 1 = 43
43 * 2 = 86
43 * 3 = 129
43 * 4 = 172
43 * 5 = 215
43 * 6 = 258
43 * 7 = 301
43 * 8 = 344
43 * 9 = 387
43 * 10 = 430

44 * 1 = 44
44 * 2 = 88
44 * 3 = 132
44 * 4 = 176
44 * 5 = 220
44 * 6 = 264
44 * 7 = 308
44 * 8 = 352
44 * 9 = 396
44 * 10 = 440

45 * 1 = 45
45 * 2 = 90
45 * 3 = 135
45 * 4 = 180
45 * 5 = 225
45 * 6 = 270
45 * 7 = 315
45 * 8 = 360
45 * 9 = 405
45 * 10 = 450

46 * 1 = 46
46 * 2 = 92
46 * 3 = 138
46 * 4 = 184
46 * 5 = 230
46 * 6 = 276
46 * 7 = 322
46 * 8 = 368
46 * 9 = 414
46 * 10 = 460

47 * 1 = 47
47 * 2 = 94
47 * 3 = 141
47 * 4 = 188
47 * 5 = 235
47 * 6 = 282
47 * 7 = 329
47 * 8 = 376
47 * 9 = 423
47 * 10 = 470

48 * 1 = 48
48 * 2 = 96
48 * 3 = 144
48 * 4 = 192
48 * 5 = 240
48 * 6 = 288
48 * 7 = 336
48 * 8 = 384
48 * 9 = 432
48 * 10 = 480

49 * 1 = 49
49 * 2 = 98
49 * 3 = 147
49 * 4 = 196
49 * 5 = 245
49 * 6 = 294
49 * 7 = 343
49 * 8 = 392
49 * 9 = 441
49 * 10 = 490

50 * 1 = 50
50 * 2 = 100
50 * 3 = 150
50 * 4 = 200
50 * 5 = 250
50 * 6 = 300
50 * 7 = 350
50 * 8 = 400
50 * 9 = 450
50 * 10 = 500

51 * 1 = 51
51 * 2 = 102
51 * 3 = 153
51 * 4 = 204
51 * 5 = 255
51 * 6 = 306
51 * 7 = 357
51 * 8 = 408
51 * 9 = 459
51 * 10 = 510

52 * 1 = 52
52 * 2 = 104
52 * 3 = 156
52 * 4 = 208
52 * 5 = 260
52 * 6 = 312
52 * 7 = 364
52 * 8 = 416
52 * 9 = 468
52 * 10 = 520

53 * 1 = 53
53 * 2 = 106
53 * 3 = 159
53 * 4 = 212
53 * 5 = 265
53 * 6 = 318
53 * 7 = 371
53 * 8 = 424
53 * 9 = 477
53 * 10 = 530

54 * 1 = 54
54 * 2 = 108
54 * 3 = 162
54 * 4 = 216
54 * 5 = 270
54 * 6 = 324
54 * 7 = 378
54 * 8 = 432
54 * 9 = 486
54 * 10 = 540

55 * 1 = 55
55 * 2 = 110
55 * 3 = 165
55 * 4 = 220
55 * 5 = 275
55 * 6 = 330
55 * 7 = 385
55 * 8 = 440
55 * 9 = 495
55 * 10 = 550

56 * 1 = 56
56 * 2 = 112
56 * 3 = 168
56 * 4 = 224
56 * 5 = 280
56 * 6 = 336
56 * 7 = 392
56 * 8 = 448
56 * 9 = 504
56 * 10 = 560

57 * 1 = 57
57 * 2 = 114
57 * 3 = 171
57 * 4 = 228
57 * 5 = 285
57 * 6 = 342
57 * 7 = 399
57 * 8 = 456
57 * 9 = 513
57 * 10 = 570

58 * 1 = 58
58 * 2 = 116
58 * 3 = 174
58 * 4 = 232
58 * 5 = 290
58 * 6 = 348
58 * 7 = 406
58 * 8 = 464
58 * 9 = 522
58 * 10 = 580

59 * 1 = 59
59 * 2 = 118
59 * 3 = 177
59 * 4 = 236
59 * 5 = 295
59 * 6 = 354
59 * 7 = 413
59 * 8 = 472
59 * 9 = 531
59 * 10 = 590

60 * 1 = 60
60 * 2 = 120
60 * 3 = 180
60 * 4 = 240
60 * 5 = 300
60 * 6 = 360
60 * 7 = 420
60 * 8 = 480
60 * 9 = 540
60 * 10 = 600

61 * 1 = 61
61 * 2 = 122
61 * 3 = 183
61 * 4 = 244
61 * 5 = 305
61 * 6 = 366
61 * 7 = 427
61 * 8 = 488
61 * 9 = 549
61 * 10 = 610

62 * 1 = 62
62 * 2 = 124
62 * 3 = 186
62 * 4 = 248
62 * 5 = 310
62 * 6 = 372
62 * 7 = 434
62 * 8 = 496
62 * 9 = 558
62 * 10 = 620

63 * 1 = 63
63 * 2 = 126
63 * 3 = 189
63 * 4 = 252
63 * 5 = 315
63 * 6 = 378
63 * 7 = 441
63 * 8 = 504
63 * 9 = 567
63 * 10 = 630

64 * 1 = 64
64 * 2 = 128
64 * 3 = 192
64 * 4 = 256
64 * 5 = 320
64 * 6 = 384
64 * 7 = 448
64 * 8 = 512
64 * 9 = 576
64 * 10 = 640

65 * 1 = 65
65 * 2 = 130
65 * 3 = 195
65 * 4 = 260
65 * 5 = 325
65 * 6 = 390
65 * 7 = 455
65 * 8 = 520
65 * 9 = 585
65 * 10 = 650

66 * 1 = 66
66 * 2 = 132
66 * 3 = 198
66 * 4 = 264
66 * 5 = 330
66 * 6 = 396
66 * 7 = 462
66 * 8 = 528
66 * 9 = 594
66 * 10 = 660

67 * 1 = 67
67 * 2 = 134
67 * 3 = 201
67 * 4 = 268
67 * 5 = 335
67 * 6 = 402
67 * 7 = 469
67 * 8 = 536
67 * 9 = 603
67 * 10 = 670

68 * 1 = 68
68 * 2 = 136
68 * 3 = 204
68 * 4 = 272
68 * 5 = 340
68 * 6 = 408
68 * 7 = 476
68 * 8 = 544
68 * 9 = 612
68 * 10 = 680

69 * 1 = 69
69 * 2 = 138
69 * 3 = 207
69 * 4 = 276
69 * 5 = 345
69 * 6 = 414
69 * 7 = 483
69 * 8 = 552
69 * 9 = 621
69 * 10 = 690

70 * 1 = 70
70 * 2 = 140
70 * 3 = 210
70 * 4 = 280
70 * 5 = 350
70 * 6 = 420
70 * 7 = 490
70 * 8 = 560
70 * 9 = 630
70 * 10 = 700

71 * 1 = 71
71 * 2 = 142
71 * 3 = 213
71 * 4 = 284
71 * 5 = 355
71 * 6 = 426
71 * 7 = 497
71 * 8 = 568
71 * 9 = 639
71 * 10 = 710

72 * 1 = 72
72 * 2 = 144
72 * 3 = 216
72 * 4 = 288
72 * 5 = 360
72 * 6 = 432
72 * 7 = 504
72 * 8 = 576
72 * 9 = 648
72 * 10 = 720

73 * 1 = 73
73 * 2 = 146
73 * 3 = 219
73 * 4 = 292
73 * 5 = 365
73 * 6 = 438
73 * 7 = 511
73 * 8 = 584
73 * 9 = 657
73 * 10 = 730

74 * 1 = 74
74 * 2 = 148
74 * 3 = 222
74 * 4 = 296
74 * 5 = 370
74 * 6 = 444
74 * 7 = 518
74 * 8 = 592
74 * 9 = 666
74 * 10 = 740

75 * 1 = 75
75 * 2 = 150
75 * 3 = 225
75 * 4 = 300
75 * 5 = 375
75 * 6 = 450
75 * 7 = 525
75 * 8 = 600
75 * 9 = 675
75 * 10 = 750

76 * 1 = 76
76 * 2 = 152
76 * 3 = 228
76 * 4 = 304
76 * 5 = 380
76 * 6 = 456
76 * 7 = 532
76 * 8 = 608
76 * 9 = 684
76 * 10 = 760

77 * 1 = 77
77 * 2 = 154
77 * 3 = 231
77 * 4 = 308
77 * 5 = 385
77 * 6 = 462
77 * 7 = 539
77 * 8 = 616
77 * 9 = 693
77 * 10 = 770

78 * 1 = 78
78 * 2 = 156
78 * 3 = 234
78 * 4 = 312
78 * 5 = 390
78 * 6 = 468
78 * 7 = 546
78 * 8 = 624
78 * 9 = 702
78 * 10 = 780

79 * 1 = 79
79 * 2 = 158
79 * 3 = 237
79 * 4 = 316
79 * 5 = 395
79 * 6 = 474
79 * 7 = 553
79 * 8 = 632
79 * 9 = 711
79 * 10 = 790

80 * 1 = 80
80 * 2 = 160
80 * 3 = 240
80 * 4 = 320
80 * 5 = 400
80 * 6 = 480
80 * 7 = 560
80 * 8 = 640
80 * 9 = 720
80 * 10 = 800

81 * 1 = 81
81 * 2 = 162
81 * 3 = 243
81 * 4 = 324
81 * 5 = 405
81 * 6 = 486
81 * 7 = 567
81 * 8 = 648
81 * 9 = 729
81 * 10 = 810

82 * 1 = 82
82 * 2 = 164
82 * 3 = 246
82 * 4 = 328
82 * 5 = 410
82 * 6 = 492
82 * 7 = 574
82 * 8 = 656
82 * 9 = 738
82 * 10 = 820

83 * 1 = 83
83 * 2 = 166
83 * 3 = 249
83 * 4 = 332
83 * 5 = 415
83 * 6 = 498
83 * 7 = 581
83 * 8 = 664
83 * 9 = 747
83 * 10 = 830

84 * 1 = 84
84 * 2 = 168
84 * 3 = 252
84 * 4 = 336
84 * 5 = 420
84 * 6 = 504
84 * 7 = 588
84 * 8 = 672
84 * 9 = 756
84 * 10 = 840

85 * 1 = 85
85 * 2 = 170
85 * 3 = 255
85 * 4 = 340
85 * 5 = 425
85 * 6 = 510
85 * 7 = 595
85 * 8 = 680
85 * 9 = 765
85 * 10 = 850

86 * 1 = 86
86 * 2 = 172
86 * 3 = 258
86 * 4 = 344
86 * 5 = 430
86 * 6 = 516
86 * 7 = 602
86 * 8 = 688
86 * 9 = 774
86 * 10 = 860

87 * 1 = 87
87 * 2 = 174
87 * 3 = 261
87 * 4 = 348
87 * 5 = 435
87 * 6 = 522
87 * 7 = 609
87 * 8 = 696
87 * 9 = 783
87 * 10 = 870

88 * 1 = 88
88 * 2 = 176
88 * 3 = 264
88 * 4 = 352
88 * 5 = 440
88 * 6 = 528
88 * 7 = 616
88 * 8 = 704
88 * 9 = 792
88 * 10 = 880

89 * 1 = 89
89 * 2 = 178
89 * 3 = 267
89 * 4 = 356
89 * 5 = 445
89 * 6 = 534
89 * 7 = 623
89 * 8 = 712
89 * 9 = 801
89 * 10 = 890

90 * 1 = 90
90 * 2 = 180
90 * 3 = 270
90 * 4 = 360
90 * 5 = 450
90 * 6 = 540
90 * 7 = 630
90 * 8 = 720
90 * 9 = 810
90 * 10 = 900

91 * 1 = 91
91 * 2 = 182
91 * 3 = 273
91 * 4 = 364
91 * 5 = 455
91 * 6 = 546
91 * 7 = 637
91 * 8 = 728
91 * 9 = 819
91 * 10 = 910

92 * 1 = 92
92 * 2 = 184
92 * 3 = 276
92 * 4 = 368
92 * 5 = 460
92 * 6 = 552
92 * 7 = 644
92 * 8 = 736
92 * 9 = 828
92 * 10 = 920

93 * 1 = 93
93 * 2 = 186
93 * 3 = 279
93 * 4 = 372
93 * 5 = 465
93 * 6 = 558
93 * 7 = 651
93 * 8 = 744
93 * 9 = 837
93 * 10 = 930

94 * 1 = 94
94 * 2 = 188
94 * 3 = 282
94 * 4 = 376
94 * 5 = 470
94 * 6 = 564
94 * 7 = 658
94 * 8 = 752
94 * 9 = 846
94 * 10 = 940

95 * 1 = 95
95 * 2 = 190
95 * 3 = 285
95 * 4 = 380
95 * 5 = 475
95 * 6 = 570
95 * 7 = 665
95 * 8 = 760
95 * 9 = 855
95 * 10 = 950

96 * 1 = 96
96 * 2 = 192
96 * 3 = 288
96 * 4 = 384
96 * 5 = 480
96 * 6 = 576
96 * 7 = 672
96 * 8 = 768
96 * 9 = 864
96 * 10 = 960

97 * 1 = 97
97 * 2 = 194
97 * 3 = 291
97 * 4 = 388
97 * 5 = 485
97 * 6 = 582
97 * 7 = 679
97 * 8 = 776
97 * 9 = 873
97 * 10 = 970

98 * 1 = 98
98 * 2 = 196
98 * 3 = 294
98 * 4 = 392
98 * 5 = 490
98 * 6 = 588
98 * 7 = 686
98 * 8 = 784
98 * 9 = 882
98 * 10 = 980

99 * 1 = 99
99 * 2 = 198
99 * 3 = 297
99 * 4 = 396
99 * 5 = 495
99 * 6 = 594
99 * 7 = 693
99 * 8 = 792
99 * 9 = 891
99 * 10 = 990

100 * 1 = 100
100 * 2 = 200
100 * 3 = 300
100 * 4 = 400
100 * 5 = 500
100 * 6 = 600
100 * 7 = 700
100 * 8 = 800
100 * 9 = 900
100 * 10 = 1000

In [ ]:
cadena =input("Ingrese la palabra a evaluar:")

cadena.lower()

Ingrese la palabra a evaluar:MAMAHUEVO

'mamahuevo'